apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-vaultk8s-job
  namespace: supplychain-bes
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/vault-k8s-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-training
      namespace: flux-training
  values:
    metadata:
      name: supplychain-vaultk8s-job
      namespace: supplychain-bes
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      role: vault-role
      address: http://20.93.235.67:8200
      authpath: besusupplychain
      policy: vault-crypto-supplychain-bes-supplychain-ro
      policydata: "{\n  \"policy\": \"path \\\"secretsv2/data/supplychain-bes/crypto/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\", \\\"create\\\", \\\"update\\\"]\n  }\n  path \\\"secretsv2/data/supplychain-bes/smartContracts/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\"]\n  }\"\n}"
      secret_path: secretsv2
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://bevel-aks-test-remove-afte-6dce89-fth6zo8x.hcp.westeurope.azmk8s.io:443
    
    rbac:
      create: True

    serviceAccount:
      create: True
      name: vault-auth
