apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-node-key-mgmt
  namespace: manufacturer-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturer-node-key-mgmt
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_key_mgmt
    sourceRef:
      kind: GitRepository
      name: flux-training
      namespace: flux-training
  values:
    metadata:
      name: manufacturer-node-key-mgmt
      namespace: manufacturer-bes
    image:
      besucontainer: hyperledger/besu:22.10.2
    vault:
      address: http://20.93.235.67:8200
      secretengine: secretsv2
      authpath: besumanufacturer
      type: hashicorp
      role: vault-role
    organisation:
      namespace: manufacturer-bes
      nodes:
        - name: manufacturer
