##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

dlt_templates:
  namespace: namespace.tpl
  aws-storageclass: storageclass.tpl
  minikube-storageclass: storageclass.tpl
  gcp-storageclass: storageclass.tpl
  azure-storageclass: azure-storageclass.tpl
