kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: store-azure-storageclass
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  skuName: StandardSSD_LRS	
  kind: Managed
