apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-tessera-job
  namespace: store-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: store-tessera-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/tessera_key_mgmt
    sourceRef:
      kind: GitRepository
      name: flux-training
      namespace: flux-training
  values:
    metadata:
      name: store-tessera-job
      namespace: store-bes
    peer:
      name: store
    image:
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
      pullPolicy: IfNotPresent
      alpineutils: ghcr.io/hyperledger/bevel-alpine-ext:latest
    vault:
      address: http://20.93.235.67:8200
      secretengine: secretsv2
      authpath: besustore
      role: vault-role
      keyprefix: store-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: data/store-bes/crypto
      type: hashicorp

